# 파이썬 라이브러리

# Numpy

In [1]:
import numpy as np

In [2]:
np.__version__

'1.18.1'

### ndarray

- 다차원 배열

In [3]:
lst = [1, 2, 3]
type(lst)

list

In [5]:
array1 = np.array(lst)
array1, type(array1), array1.shape

(array([1, 2, 3]), numpy.ndarray, (3,))

In [8]:
array2 = np.array([[1, 2, 3],
                   [2, 3, 4]])

type(array2), array2.shape

(numpy.ndarray, (2, 3))

row, 1

column, 0

In [14]:
# shape 확인
array2.shape

(2, 3)

In [12]:
# 차원 확인
array2.ndim

2

In [13]:
# 전체 갯수
array2.size

6

### ndarray type

In [15]:
array1.dtype

dtype('int32')

In [16]:
array2.dtype

dtype('int32')

In [18]:
array3 = np.array([1, 2, 3.0])
type(array3), array3.dtype

(numpy.ndarray, dtype('float64'))

- dtype이 array3의 경우 foat64이다.

- 정수와 실수가 섞여있으면 실수가 된다.

In [19]:
array4 = np.array([1, 2, 'test'])
type(array4), array4.dtype

(numpy.ndarray, dtype('<U11'))

- ndarray는 같은 타입으로 되어 있다.

- 원소의 자료형은 일치되어야 한다.

### 형변환

- astype()

In [22]:
# ndarray type 변경
array_int = np.array([1, 2, 3])
array_int.dtype

array_float = array_int.astype('float64')
array_float.dtype, array_float                             

(dtype('float64'), array([1., 2., 3.]))

In [23]:
array_int1 = array_float.astype('int32')
array_int1.dtype

dtype('int32')

In [25]:
array_float1 = np.array([1.1, 2.1, 3.1], dtype=np.int64)
array_float1, array_float1.dtype

(array([1, 2, 3], dtype=int64), dtype('int64'))

## 연습 01

Numpy를 이용해 다음과 같은 3차원 배열을 만드록, 배열의 크기, 차원, 전체 요소 개수를 확인해 보자

In [32]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

In [33]:
print(f"배열의 크기: {arr.shape}")
print(f"배열의 차원: {arr.ndim}")
print(f"배열의 개수: {arr.size}")

배열의 크기: (2, 2, 2)
배열의 차원: 3
배열의 개수: 8


## ndarray 생성

In [34]:
# arange() 함수
seq_array = np.arange(10)
seq_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
seq_array.dtype, seq_array.shape

(dtype('int32'), (10,))

In [40]:
# zeros 함수
zero_array = np.zeros((3, 2), dtype='int32')
zero_array

array([[0, 0],
       [0, 0],
       [0, 0]])

In [41]:
zero_array.shape

(3, 2)

In [42]:
# ones() 함수
one_array = np.ones((3, 2))
one_array.dtype

dtype('float64')

In [44]:
# dtype를 지정안하면 float64가 된다.
one_array = np.ones((3, 2), dtype='int32')
one_array.dtype

dtype('int32')

In [47]:
# full() 함수
# 일정한 값이 채워진 ndarray 생성
full_array = np.full((5, 5), 2)
full_array

array([[2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2]])

In [51]:
# random.rand()
rand_array = np.random.rand(2, 3)
rand_array

array([[0.5465113 , 0.80570571, 0.04860704],
       [0.82828504, 0.5585054 , 0.79020076]])

In [53]:
# random.randint()
# 1~10 사이의 값 중 하나를 출력
rand_int = np.random.randint(1, 10)
rand_int

5

In [55]:
# random한 정수값을 size 크기로 출력
rand_array = np.random.randint(2, 10, size=(2, 3))
rand_array

array([[8, 5, 3],
       [2, 2, 9]])

## 연습 02

1, 2, 3, .... 50이 담긴 배열을 생성하시오.

In [56]:
arr = np.arange(1, 51)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

## ndarray 차원(모양) 변경

- reshape()

In [60]:
array1 = np.arange(10)
print(array1)

array2 = array1.reshape(2, 5)
print(array2)

array3 = array1.reshape(5, 2)
print(array3)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


- size가 맞지 않으면 에러가 발생한다.
    
    - ex) ValueError: cannot reshape array of size 10 into shape (3, 3)

In [62]:
# 자동으로 크기 찾기
# -1 을 사용
array2 = array1.reshape(2, -1)
print(array2)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [68]:
# 모양을 통일하기
# 1차원을 3차원으로 변경
array1 = np.arange(8)
array3d = array1.reshape((2, 2, 2))

# list 타입으로 변경
array3d.tolist()

[[[0, 1], [2, 3]], [[4, 5], [6, 7]]]

In [69]:
type(array3d), type(array3d.tolist())

(numpy.ndarray, list)

- ndarray 형태 통일하기

In [71]:
array5 = array3d.reshape(-1, 1)
array5, array5.ndim

(array([[0],
        [1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7]]),
 2)

In [73]:
array6 = array1.reshape(-1, 1)
array6, array6.ndim

(array([[0],
        [1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7]]),
 2)

## 인덱싱 & 슬라이싱 & 팬시 인덱싱 & 불린 인덱싱

### 인덱싱

In [87]:
# 1차원
array = np.arange(start=1, stop=10)
array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [81]:
# 인덱싱
v = array[2]
v, type(v)

(3, numpy.int32)

- 그냥 int가 아닌 numpy.int32이다.

In [85]:
array[-1], array[8]

(9, 9)

In [86]:
array[0] = 10
array

array([10,  2,  3,  4,  5,  6,  7,  8,  9])

In [89]:
# 2차원
array = np.array([[1, 2, 3], [4, 5, 6]])
array

array([[1, 2, 3],
       [4, 5, 6]])

In [90]:
array[0]

array([1, 2, 3])

In [92]:
array[0][1]

2

In [93]:
array[0, 1]

2

In [102]:
array1d = np.arange(1, 10)
array2d = array1d.reshape((3, 3))

print(array2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [98]:
array2d[0]

array([1, 2, 3])

In [99]:
array2d[1, 0]

4

In [101]:
array2d[2, 2]

9

- 행, 열

- axis 0, axis 1

### 슬라이싱

In [106]:
array = np.arange(1, 10)
array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [110]:
array[0:3], array[:3]

(array([1, 2, 3]), array([1, 2, 3]))

In [113]:
array[:], array[::]

(array([1, 2, 3, 4, 5, 6, 7, 8, 9]), array([1, 2, 3, 4, 5, 6, 7, 8, 9]))

In [114]:
array[::2]

array([1, 3, 5, 7, 9])

In [115]:
array[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

In [118]:
# 2차원 슬라이싱
array = np.arange(1, 10).reshape(3, 3)
print(array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [119]:
array[0:2, 0:2]

array([[1, 2],
       [4, 5]])

In [120]:
array[:, :]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [123]:
array[:2, :3]

array([[1, 2, 3],
       [4, 5, 6]])

In [124]:
array[1:3, 0:3]

array([[4, 5, 6],
       [7, 8, 9]])

In [125]:
array[1:3, :]

array([[4, 5, 6],
       [7, 8, 9]])

In [126]:
array[:2, 1:]

array([[2, 3],
       [5, 6]])

In [127]:
array[0], array[0].shape

(array([1, 2, 3]), (3,))

### 팬시 인덱싱

In [130]:
# 1차원 펜시 인덱싱
array = np.arange(1, 10)
print(array)

[1 2 3 4 5 6 7 8 9]


In [131]:
array[[2, 4, 7]]

array([3, 5, 8])

- 인덱스의 목록을 이용하여 값을 가져오는것

In [132]:
array = np.arange(1, 10).reshape(3, 3)
print(array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [133]:
array[[0, 1], 2]

array([3, 6])

In [134]:
array[[0, 1], 0:2]

array([[1, 2],
       [4, 5]])

In [135]:
array[[0, 2], [0, 2]]

array([1, 9])

In [137]:
# 열이 주어지지 않은 경우
# 전부 출력
array[[0, 1]]

array([[1, 2, 3],
       [4, 5, 6]])

### 불린 인덱싱

In [140]:
array = np.arange(1, 10)
array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [139]:
array>5

array([False, False, False, False, False,  True,  True,  True,  True])

In [142]:
# True인 값들만 출력됨
array[array>5]

array([6, 7, 8, 9])

- 조건에 따른 필터의 느낌

#### 예시

In [147]:
name = np.array(['홍길동', '박철수', '이혜수', '임유리', '김영원'])
name_score = np.array([[60, 60], [70, 70], [80, 80], [90, 90], [100, 100], ])

print(name_score)

# name이 홍길동 인것의 점수만 출력
name_score[name == '홍길동']

[[ 60  60]
 [ 70  70]
 [ 80  80]
 [ 90  90]
 [100 100]]


array([[60, 60]])

### 연습문제

- 사람의 키와 몸무게가 주어졌을때, BMI 지수를 구하시오

BMI = 몸무게 / 키**2

In [180]:
drive_path = r"c:/Apps/temp/"
data = np.loadtxt(drive_path + "height_weight.txt", delimiter=",")

# cm => m
h = data[0] / 100
w = data[1]

bmi = w/h**2

print(bmi)

[21.37153104 27.07018468 25.86122449 24.20652885 16.03543423 20.14486193
 23.14392095 21.69720651 23.62028791 25.59220998]


## 정렬

In [188]:
# np.sort()
# 정렬된것을 반환함
org_array = np.array([3, 5, 2, 1, 9])
sort_array = np.sort(org_array)
sort_array

array([1, 2, 3, 5, 9])

In [189]:
print(org_array)

# .sort()
# 원본을 정렬시킴
org_array.sort()
print(org_array)

[3 5 2 1 9]
[1 2 3 5 9]


In [190]:
# 정렬해서 내림차순을 출력
np.sort(org_array)[::-1]

array([9, 5, 3, 2, 1])

In [196]:
array = np.array([[8, 12],
                  [7, 1]])

# row 방향 정렬
# 행이 정렬
sort_array = np.sort(array, axis=0)
sort_array

array([[ 7,  1],
       [ 8, 12]])

In [197]:
# column 방향 정렬
# 열이 정렬
sort_array = np.sort(array, axis=1)
sort_array

array([[ 8, 12],
       [ 1,  7]])

In [201]:
# np.argsort()
# 인덱스를 반환
org_array = np.array([3, 5, 2, 1, 9])
print(org_array)

sort_array = np.sort(org_array)
sort_index = np.argsort(org_array)

print(sort_array)
print(sort_index)

[3 5 2 1 9]
[1 2 3 5 9]
[3 2 0 1 4]


- 정렬된 값이 이전에 어떤 인덱스 였는지 확인할 수 있다.

- 예를들어 숫자 1은 정렬되기 전에 인덱스 3 이었다.

In [203]:
# argsort() 활용
name = np.array(['홍길동', '박철수', '이혜수', '임유리', '김영원'])
name_score = np.array([78, 95, 84, 98, 88])

sort_index = np.argsort(name_score)
# 성적 순으로 이름을 출력
print(name[sort_index])

['홍길동' '이혜수' '김영원' '박철수' '임유리']


## 연산

In [205]:
# ndarray 연산
array = np.arange(5)
print(array)

array+100

[0 1 2 3 4]


array([100, 101, 102, 103, 104])

In [206]:
array + array

array([0, 2, 4, 6, 8])

In [207]:
array * 2

array([0, 2, 4, 6, 8])

- 단 모양이 다르면 않된다

In [211]:
np.add(array, array)

array([0, 2, 4, 6, 8])

In [212]:
array == array

array([ True,  True,  True,  True,  True])

In [213]:
array > array

array([False, False, False, False, False])