# Numpy

In [1]:
import numpy as np

## 곱(내적)

In [3]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])

b = np.array([[7, 8],
              [9, 10],
              [11, 12]])

In [4]:
a.shape, b.shape

((2, 3), (3, 2))

In [5]:
# 행렬 곱
c = np.dot(a, b)
c

array([[ 58,  64],
       [139, 154]])

- a * b 를하면 에러가 발생한다. 크기가 맞지 않기 때문이다.

## 전치 행렬

In [12]:
# 전치 행렬
# 행과 열을 바꾼다.
print(a)

print(a.T)
print(np.transpose(a))

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]
[[1 4]
 [2 5]
 [3 6]]


## U 함수

- 유니버셜 함수

In [14]:
array = np.arange(1, 11)
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [15]:
# 합계
array.sum()

55

In [19]:
arr = np.arange(1, 11).reshape(2, 5)
arr[0], arr[0].sum()

(array([1, 2, 3, 4, 5]), 15)

In [20]:
# 평균
array.mean()

5.5

In [21]:
# 절대값
array = np.array([-1, -2, 3, 4, -5])
np.abs(array)

array([1, 2, 3, 4, 5])

### 연습 04



In [25]:
drive_path = r"c:/Apps/temp/"
data = np.loadtxt(drive_path + "ratings_small.txt", delimiter="::", dtype=np.int64)

In [31]:
# 모양, 차원, 크기
data.shape, data.ndim, data.size

((300001, 4), 2, 1200004)

In [47]:
print(data[0])

print(f"user id: {data[0][0]}")
print(f"movie id: {data[0][1]}")
print(f"score: {data[0][2]}")

[        1      1193         5 978300760]
user id: 1
movie id: 1193
score: 5


In [44]:
# 전체 평점 평균
data[:, 2].mean()

3.5613081289729034

In [60]:
# user id가 1인 경우의 영화 평점 평균
data[data[:, 0] == 1][:, 2].mean()

4.188679245283019

In [ ]:
# user id별 영화 평점 평균
# 유니크 아이디 가져오기
np.unique(data[:, 0])

score = []
user_id = np.unique(data[:, 0])
for i in user_id:
    user_score_mean = data[data[:, 0] == i][:, 2].mean()
    score.append([i, user_score_mean])
    
score

In [ ]:
# 평점 평균이 4 이상인 user id
arr = np.array(score)

arr[arr[:, 1] >= 4][:, 0].astype('int64')

In [96]:
# text로 저장
np.savetxt(drive_path + "user_id_mean.csv", score, delimiter=",", fmt="%.3f")

### linspace()

In [97]:
# linspace()
arr = np.linspace(0, 10, 5)
arr

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

### Numpy 배열의 확장

- append()

In [100]:
# 1차원의 경우
a = np.array([1, 2, 3])
b = np.append(a, [4, 5, 6])
b

array([1, 2, 3, 4, 5, 6])

In [106]:
# 2차원의 경우
a = np.array([[1, 2], [3, 4]])

b = np.append(a, [[9, 9]], axis=0)
print(b)
print("-"*8)
c = np.append(a, [[9], [9]], axis=1)
print(c)

[[1 2]
 [3 4]
 [9 9]]
--------
[[1 2 9]
 [3 4 9]]


### Numpy 배열의 삭제

- np.delete()